# Generated by Django 5.1.6 on 2025-02-18 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reagostation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FullName', models.CharField(max_length=50)),
                ('EmailAddress', models.CharField(max_length=50)),
                ('PhoneNumber', models.CharField(max_length=14)),
                ('Gender', models.CharField(max_length=30)),
                ('DateofBirth', models.CharField(max_length=22)),
                ('Course', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=30)),
                ('Agree', models.CharField(max_length=1)),
            ],
        ),
    ]
